"""Add receipt_url to expenses

Revision ID: bc5948ec175c
Revises: e2f1515c5b92
Create Date: 2026-06-25 17:33:18.659783

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc5948ec175c"
down_revision: Union[str, Sequence[str], None] = "e2f1515c5b92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("receipt_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "receipt_url")
    # ### end Alembic commands ###
