"""add default_currency to user

Revision ID: e2f1515c5b92
Revises: 426c8fae955a
Create Date: 2026-06-21 15:50:04.679383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f1515c5b92'
down_revision: Union[str, Sequence[str], None] = '426c8fae955a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_currency', sa.String(), nullable=True))
    op.execute("UPDATE users SET default_currency = 'INR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_currency')
    # ### end Alembic commands ###
